### PR TITLE
Check for the return value of all malloc and strdup calls

### LINKED ISSUE #51: Unchecked malloc return value
There are 3 `malloc()` calls in the code with no `NULL` checks:

* [`src/lib/editorconfig.c:334`](https://github.com/editorconfig/editorconfig-core-c/blob/a8fae2375e67887bd73baa11d921339f24e8b9a9/src/lib/editorconfig.c#L334)
* [`src/lib/editorconfig.c:341`](https://github.com/editorconfig/editorconfig-core-c/blob/a8fae2375e67887bd73baa11d921339f24e8b9a9/src/lib/editorconfig.c#L341)
* [`src/bin/main.c:144`](https://github.com/editorconfig/editorconfig-core-c/blob/a8fae2375e67887bd73baa11d921339f24e8b9a9/src/bin/main.c#L144)

There are also about a dozen calls to `strdup()` and `strndup()` with the same problem.

### PR DESCRIPTION
**Pull request by xuhdev**
Fix #51 

cc @craigbarnes

### CODE REVIEW

**Comment by xuhdev** [comment]
Related troydhanson/uthash#174

cc @craigbarnes

**Comment by craigbarnes** [comment]
This seems to cover the ones in the `editorconfig` program. The `strn?dup()` calls still seem to be unchecked though:

```
$ git grep '\<strn?dup\(' -- *.c
src/bin/main.c:96:            char*             argvi = strdup(argv[i]);
src/bin/main.c:149:                file_paths[path_count + i - argc] = strdup(argv[i]);
src/bin/main.c:204:            full_filename = strdup(full_filename);
src/lib/ec_glob.c:377:        num_string = strndup(substring_start, substring_length);
src/lib/editorconfig.c:80:        nv->name = strdup(name);
src/lib/editorconfig.c:82:        nv->value = strdup(value);
src/lib/editorconfig.c:300:        *directory = strndup(absolute_path,
src/lib/editorconfig.c:304:        *filename = strndup(path_char+1, strlen(path_char)-1);
src/lib/editorconfig.c:336:    currdir = strdup(path);
src/lib/editorconfig.c:453:    hfp.full_filename = strdup(full_filename);
src/lib/editorconfig.c:473:            eh->err_file = strdup(*config_file);
```

**Comment by xuhdev** [comment]
The dependency issue in uthash has been resolved. Will continue fixing here.

**Comment by xuhdev** [comment]
@craigbarnes Should be good now. Feel free to do some tests! Thanks!

**Comment by craigbarnes** [comment]
That seems to improve it a lot, but there seems to be a few cases of error codes being propagated but ignored by callers.

For example, the call to `split_file_path()` in `editorconfig_parse()` discards the return value, which could be `-1` to indicate that `strndup()` failed and `hfp.editorconfig_file_dir` is `NULL`. It then passes `hfp` to `ini_parse()`, which passes it on to `ini_callback()`, which then dereferences the NULL pointer.

**Comment by xuhdev** [comment]
@craigbarnes Thanks for pointing out. I've reopened #51

**Pull request merged**
